### ISSUE TITLE
Use technical terms from Solid TRs

### ISSUE THREAD

**Issue by csarven** [solid/solid-wg-charter#3]
Definition of Solid "pod" is not defined by the W3C Solid Community Group - none of the over 20 Work Items ( https://solidproject.org/TR/ ) require it as part of its conformance model or towards quality assurance. The conclusion of the CG is that the term is imprecise and unnecessary.

I recommend that the charter omits "pod" in favour of using terms from definitions from the Solid Technical Reports so that the context and the purpose of the proposal can be better understood.

**Comment by jeff-zucker** [comment]
In my mind a Pod is a storage controlled by a WebID.  Since a storage may be controlled by multiple WebIDs, and a WebID may have multiple storages, this situation is possible:                                                               
                                                                                
  Pod1 = <#WebIDa> solid:owner <#Storage1>.                                     
  Pod2 = <#WebIDa> solid:owner <#Storage2>.                                     
  Pod3 = <#WebIDb> solid:owner <#Storage2>.                                     
                                                                                
In this example, the owner of WebIDa has two Pods and Pod2 is controlled by two WebID owners.  If a single person owns both WebIDs, that person would have three Pods, although they might be the only one who knows that.  All of this would be true regardless of what provider or host is associated with the WebID or the Storage.

**Comment by laurensdeb** [comment]
Given the fact we don’t use the terminology “Pod” in a normative sense (or provide a formal definition for the term in any of the CG specifications). I would agree that we should be avoiding a significant emphasis on the concept “Solid Pod” in the charter, as is currently very much the case in the preface of the document.
