### ISSUE TITLE
State what Solid tries to standardise in more precise/layman's terms + expand scope

### ISSUE THREAD

**Issue by tomhgmns** [solid/solid-wg-charter#32]
Currently, the charter states that Solid tries to standardise "[...] a space where individuals can maintain their autonomy, control their data and privacy, and choose applications and services to fulfil their needs."

This is fairly abstract and focusses solely on "individuals".

I suggest to simply say that Solid aims to standardise accounts for users and organisations.

In addition, in my view, the reason of existence of Solid is to ensure that there is a loose coupling between 
* identifiers of accounts,
* login methods of accounts, 
* authorisation methods of accounts,
* storage locations of accounts and
* apps where you can use those accounts

The idea is that you 
* can share access to data with other accounts
* can login to apps with those accounts and share access to data with those apps

Regardless in which store your data is stored.

I think this should be made more explicit in the working group charter.

**Comment by jeff-zucker** [comment]
I agree that it is important to mention organizations.  I do not agree that statement should be removed.  Solid has  social, semantic, and technical levels and I believe we should always put the social level first.  We don't want separation of apps and data because that's the way God intended it, but because it contributes to the empowerment of individuals and organizations.

**Comment by tomhgmns** [comment]
Sure, but I think we have to be more precise in the words that we use. 

For us, this all makes sense, but for other W3C Advisory Committee Representatives, the way how Solid is currently described might be confusing.

**Comment by jeff-zucker** [comment]
Perhaps take the existing sentence as a lead in to the technical description.   Solid tries to standardize a space where individuals and organizations can maintain their autonomy ... Solid seeks to support such a space  by decoupling storage locations and accounts, etc.

**Comment by melvincarvalho** [comment]
Possibly more dispassionate text:

From

> Solid adds to existing Web standards to enable user control: "to realise a space where individuals can maintain their autonomy, control their data and privacy, and choose applications and services to fulfil their needs."

to

> Solid aims to enhance existing web standards to prioritize user autonomy, enabling individuals to retain control over their data and privacy, and freely select applications and services that best meet their requirements.

**Comment by csarven** [comment]
Thanks all. I've taken all of your suggestions and reworked the initial paragraphs of motivation/background in this PR: https://github.com/solid/solid-wg-charter/pull/34 . Please review.

I acknowledge that editing is a continuous process but we can't indefinitely edit this particular part either. I recommend that we run with what we have in this section if there are no objections or glaring errors that should be resolved.

Below are some specific responses that I've kept in mind towards that PR.

---

>This is fairly abstract and focusses solely on "individuals".

Considering the context is the second sentence of motivation/background, I'd consider it to be a reasonable amount of abstraction to help the reader dive in.

Here is an alternative intro from the LDN spec https://www.w3.org/TR/ldn/#introduction - while we were working on Solid - that can work just as well:

>Data on the Web should not be locked in to particular systems or be only readable by the applications which created it. Users should be free to switch between applications and share data between them.

Which seems closer to your intention.

Melvin has it right re *enabling* individuals, and that's aligned with the original text. Like the Web, it is to empower society. Individuals are first in the priority of constituencies, and that is clear in [Ethical Web Principles](https://www.w3.org/TR/ethical-web-principles/). Individuals are at the centre of Solid, and they are the users when it comes to interactions. An organisation or a group is not a user in and of itself in that sense, but individuals may indeed be acting as a member or controlling an organisation.

It'd better to emphasise *communities* rather than organisations which would be in line with benefiting society.

>I suggest to simply say that Solid aims to standardise accounts for users and organisations.

"Accounts" may be not be the most representative notion, and I worry that readers will be approaching it with their existing mental models/behaviours which may not particularly align with what's intended in Solid.

There is a whole paragraph on CG's incubation of the TRs - efforts towards standardisation - with emphasis on major classes of products.
